### PR TITLE
Implement katello-ssl-tool via console_scripts

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
There have been a lot of PRs opened recently. Some context would help me. As I understand things, this is a codebase we do not want to re-use in the future for a variety of reasons. What is the context of making changes to an otherwise stable codebase here? I think that will help with reviews.

**Comment by ekohl** [comment]
https://github.com/Katello/katello-certs-tools/pull/17#issuecomment-630854316

**Comment by ekohl** [comment]
It is odd that it doesn't appear to work. AFAIK we use this all over the time on EL7.

**Comment by ekohl** [comment]
The problem was that it used distutils rather than setuptools.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
