### PR TITLE
Rewrite RPM version comparison code

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like it's not picking up some files and keep regenerating `-5`.

**Comment by ekohl** [comment]
EL8 fails on the same thing as https://github.com/Katello/katello-certs-tools/pull/38. https://github.com/Katello/katello-certs-tools/pull/37 would fix this. This patch makes part of #37 redundant.

**Comment by evgeni** [comment]
I would prefer getting #37 in, so it can be backported to 4.3 and older releases. And then get this one in.

**Comment by ekohl** [comment]
I'd be fine with that. The conflict resolution `git rm -f` is fairly trivial.

**Review by evgeni — COMMENTED** [review]
LGTM!

**Review by ehelms — APPROVED** [review]
@ekohl anything else you wanted to do to this PR since the merge of the other PR?

**Comment by ekohl** [comment]
Nope, I finally have green tests which was holding it back. Turns out I was missing a path prefix so the globbing didn't work. I'm so happy we at least have a basic test suite now.

**Pull request merged**
